spring:
  profiles:
    active: local

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  cache:
    redis:
      time-to-live: 600000

mybatis-plus:
  type-aliases-package: com.easy.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      table-prefix: tb_

role-path-permissions:
  permissions:
    ROLE_ADMIN:
      - "/admin/"
    ROLE_USER:
      - "/user/"
    ROLE_ARTIST:
      - "/artist/"
      - "/user/"
