@startuml
title 管理端登录活动图

start

:管理员提交登录请求;

:根据管理员账户查询管理员信息;

if (管理员账户是否存在?) then (否)
    :返回"账户不存在";
    stop
endif

:MD5加密输入的密码;

if (查询数据库判断密码是否正确?) then (否)
    :返回"密码错误";
    stop
endif


:生成JWT令牌;

:将token存入Redis (有效期10分钟);

:返回token及成功信息;

:登录成功;

stop

@enduml
